### ISSUE TITLE
A2plus and network paths

### ISSUE THREAD

**Issue by Luciniki** [FreeCAD/FreeCAD-addons#300]
Good morning,

when I try to import parts from my office's internal network (e.g. "\\192.168.1.100\spb\Shares\Suppliers\Pneumatic_Aluminum_Spare_Parts\DIERRE\PARTI FREECAD\Extruded_3D\45x45_2A" I get this error:

17:04:20  Initializing A2plus Workbench v0.4.65.
17:37:40  Running the Python command 'a2p_ImportPart' failed:
Traceback (most recent call last):
  File "C:\Users\LUCIANO\AppData\Roaming\FreeCAD\Mod\A2plus\.\a2p_importpart.py", line 725, in Activated
    importedObject = importPartFromFile(doc, filename)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LUCIANO\AppData\Roaming\FreeCAD\Mod\A2plus\.\a2p_importpart.py", line 341, in importPartFromFile
    relativePath = prefix+os.path.relpath(absPath, assemblyPath)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 766, in relpath

path is on mount '\\\\192.168.1.100\\spb', start on mount 'D:'

**Comment by luzpaz** [comment]
@Luciniki  Is this a A2+ issue or FreeCAD issue ?

**Comment by PhoneDroid** [comment]
Seems like an issue with the addon.
